# Generated by Django 6.0.4 on 2026-04-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['merchant', 'key'], name='payouts_ide_merchan_4d8fc8_idx'),
        ),
    ]
