# Generated by Django 6.0.4 on 2026-04-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_alter_payout_options_idempotencykey_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idempotencykey',
            name='response_body',
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='request_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('HOLD', 'Hold'), ('DEBIT', 'Debit'), ('RELEASE', 'Release')], max_length=10),
        ),
    ]
